
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 17
#define YY_END_OF_BUFFER 18
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[387] =
    {   0,
        0,    0,   18,   17,   15,   17,   17,   17,   17,   17,
       17,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    8,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    4,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    7,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   11,    0,    0,
        0,    0,    0,    0,   12,    0,    0,    0,    0,    0,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    6,    0,    0,    0,    0,
        0,    0,    9,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   13,    0,    0,    0,    0,    5,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   14,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    1,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   19,   20,    1,   21,

        1,   22,    1,    1,   23,    1,    1,   24,   25,   26,
       27,    1,    1,   28,   29,    1,   30,    1,   31,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[32] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[468] =
    {   0,
        0,   28, 1239, 1240, 1240, 1234,   11, 1218, 1208, 1211,
       10, 1240, 1213, 1212, 1206,    0, 1200, 1209,    1, 1209,
        1,    2, 1207,    3, 1224, 1203, 1222, 1203, 1220, 1200,
        6,    4,   32, 1218, 1217,   42,   43,   55,   56, 1193,
       59,    8,   69, 1215,   47,   57,   79,   80, 1214,   70,
       71,   90,   91,   94,   72,  104,   81,   92,  114, 1191,
      105,  106,  116,  118, 1212,  107,  128,  129,  130,  140,
      141,  142,  144,  151,  152,  153,  155,  165,  166,  167,
      172,  176,  177,  178,  188,  189,  190,  195,  194, 1126,
      204,  205,  206,  208,  215,  216,  217,  219,  229,  230,

      231,  235,  236,  245,  246,  247,  251,  254,  261,  262,
      263,  273,  274,  275,  280,  279,  289,  290,  291,  293,
      296,  306,  307,  308,  312,  316,  326,  327,  328,  333,
      332,  342,  343,  344,  348,  349,  358,  359,  360,  364,
      367,  368,  374,  384,  385,  386,  391,  390,  400,  401,
      404,  402,  414,  415,  416,  426,  427,  428,  432,   49,
      134,  437,  442,  446,  447,  448,  462,  463,  464,  467,
      477,  478,  479,  484,  483,  493,  494,  497,  495,  507,
      508,  509,  182,  200,  513,  521,  525,  541,  523,  542,
      551,  552,  241,  256,  556,  543,  564,  544,  580,  267,

        0,  285,  318,  591,  601,  338,  565,  585,  613,  379,
      396,  617,  566,  618,  628,  581,  583,  638,  639,  407,
      420,  643,  629,  651,  489,    0,  652, 1116,  500,  596,
      662,  657,  615,  631,  678,  667,    0,  695,  697,  699,
      709,  722,  723,  701,  703,  727,  725,  729,  736,  739,
      749,  741,  762,  763,  764,  765,  773,  743,  774,  785,
      787,  789,  766,  790,  792,  793,  804,  806,  808, 1116,
      810,  812,  817,  819,  821,  823,  836,    0,  653, 1107,
      838,  840,  853,  835,  855,  845,  847,  849,  872,  882,
      857,  895,  874,  876,  897,  899,  912,  894,    0,    0,

        0,  775,  906,  905,  928,  908,  917,  932,  930, 1094,
      934,  941,  943,  945,  947,  949,  962,  964, 1001,  966,
      968,  970,  972,  974,  976,  989,  991,  993,  995, 1006,
      990,    0,    0,    0,    0,    0,    0,    0,  988, 1022,
     1007, 1008, 1032, 1024,  965, 1026, 1028, 1034, 1037, 1041,
      937, 1043, 1045, 1047, 1058, 1049, 1051, 1053, 1060,    0,
        0,    0,    0, 1062, 1078, 1054,  895,  865, 1080, 1083,
     1085, 1087, 1089, 1090, 1091, 1092, 1102,  855, 1093, 1106,
     1110, 1101, 1112, 1121, 1123, 1240, 1131,  858,  850,  824,
      813,  794,  744,  704,  683,  681,  679,  640,  633,  619,

      582,  567,  553,  530,  528,  522,  470,  449,  438,  433,
      380,  369,  354,  322,  313,  295,  210,  171,  146,  124,
     1133, 1135,  115,   83,   38, 1137, 1139, 1141, 1143, 1145,
     1147, 1149, 1151,   36, 1153, 1155, 1157, 1159, 1161, 1163,
     1165, 1167, 1169, 1171, 1173, 1175, 1177, 1179,   18, 1181,
     1183, 1185, 1187, 1189, 1191, 1193, 1195, 1197, 1199, 1201,
     1203, 1205, 1207, 1209, 1211,    9,    7
    } ;

static const flex_int16_t yy_def[468] =
    {   0,
      387,  387,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  388,  386,  386,  386,  386,  386,  386,
      389,  386,  390,  386,  386,  386,  388,  386,  391,  386,
      392,  386,  393,  386,  386,  389,  386,  394,  386,  386,
      390,  386,  395,  396,  386,  397,  386,  391,  386,  386,
      386,  392,  386,  398,  386,  386,  393,  386,  399,  386,
      400,  386,  394,  386,  401,  386,  402,  386,  395,  386,
      386,  396,  386,  397,  386,  397,  386,  386,  403,  386,
      386,  404,  386,  398,  386,  405,  386,  406,  386,  399,

      386,  400,  386,  400,  386,  386,  407,  386,  401,  386,
      402,  386,  402,  386,  386,  408,  386,  409,  386,  410,
      403,  386,  403,  386,  411,  404,  386,  404,  386,  386,
      412,  386,  405,  386,  406,  386,  406,  386,  386,  413,
      386,  414,  407,  386,  407,  386,  386,  415,  386,  416,
      408,  386,  408,  386,  409,  386,  409,  386,  410,  386,
      410,  386,  386,  386,  386,  411,  386,  386,  417,  412,
      386,  412,  386,  386,  418,  386,  419,  413,  386,  413,
      386,  414,  386,  414,  386,  386,  386,  415,  386,  415,
      386,  416,  386,  416,  386,  386,  386,  386,  420,  386,

      164,  386,  421,  386,  204,  422,  386,  423,  417,  386,
      417,  386,  386,  424,  418,  386,  418,  386,  419,  386,
      419,  386,  386,  425,  386,  187,  187,  227,  386,  426,
      386,  231,  427,  386,  386,  386,  197,  386,  428,  386,
      240,  429,  420,  386,  420,  386,  386,  430,  431,  386,
      250,  432,  433,  423,  386,  423,  386,  386,  424,  386,
      424,  386,  386,  434,  386,  425,  386,  425,  386,  231,
      386,  435,  436,  386,  437,  438,  439,  235,  235,  279,
      386,  440,  386,  283,  441,  386,  442,  443,  386,  289,
      444,  445,  386,  446,  447,  448,  386,  297,  298,  298,

      298,  386,  449,  386,  434,  386,  434,  386,  386,  274,
      450,  451,  452,  386,  453,  453,  453,  453,  283,  386,
      454,  455,  386,  456,  457,  458,  459,  460,  461,  386,
      330,  331,  331,  331,  298,  298,  298,  298,  298,  449,
      386,  449,  386,  386,  314,  453,  453,  453,  453,  453,
      323,  462,  463,  464,  386,  465,  465,  465,  465,  331,
      331,  331,  331,  331,  386,  466,  350,  355,  465,  465,
      465,  465,  465,  466,  386,  466,  386,  373,  386,  467,
      467,  386,  467,  386,  386,    0,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,

      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386
    } ;

static const flex_int16_t yy_nxt[1272] =
    {   0,
      386,    5,   24,   31,   33,   24,   48,    6,   31,  382,
       64,  375,   37,   37,   38,   46,   46,   47,    7,   28,
      341,   29,   25,   32,   34,    8,    9,   10,   11,    5,
       65,   13,   49,   18,   33,    6,   14,   19,  306,   20,
      267,   51,   51,   52,   55,   55,    7,   56,   56,   70,
      200,  200,   71,    8,    9,   10,   11,   55,   39,   70,
       56,   41,   71,   36,   36,   58,   58,   59,   62,   62,
       63,   43,   76,   76,   55,   77,   77,   56,   67,   67,
       68,   70,   48,   88,   71,  260,   89,   45,   45,   73,
       73,   74,   76,   53,   88,   77,   54,   89,   50,   50,

       79,   79,   80,   82,   82,   83,   84,   91,   91,   97,
       92,   92,   98,   86,   86,   87,   88,  255,   91,   89,
       64,   92,   57,   57,   61,   61,  244,   94,   94,   95,
       97,   97,   69,   98,   98,  200,  200,   66,   66,  100,
      100,  101,   70,  102,  106,   71,  106,  107,  220,  107,
      104,  104,  105,  106,   75,   76,  107,  111,   77,   72,
       72,  109,  109,  110,  113,  113,  114,  115,  115,  115,
      116,  116,  116,  216,  117,   78,   78,  118,  117,  117,
       84,  118,  118,  225,  225,   81,   81,   86,   86,   87,
      119,  119,  119,  120,  120,  120,  121,   88,   85,   85,

       89,  225,  225,  123,  123,  124,   91,  126,  130,   92,
      130,  131,  210,  131,  128,  128,  129,  130,   96,   97,
      131,  135,   98,   93,   93,  133,  133,  134,  137,  137,
      138,  139,  139,  139,  140,  140,  140,  102,  141,   99,
       99,  142,  236,  236,  104,  104,  105,  141,  141,  106,
      142,  142,  107,  143,  103,  103,  147,  236,  236,  148,
      145,  145,  146,  147,  147,  111,  148,  148,  200,  200,
      108,  108,  113,  113,  114,  149,  149,  149,  150,  150,
      150,  151,  115,  112,  112,  116,  247,  247,  153,  153,
      154,  117,  155,  119,  118,  159,  120,  193,  121,  157,

      157,  158,  161,  161,  162,  123,  123,  124,  163,  163,
      163,  164,  164,  164,  125,  189,  122,  122,  126,  247,
      247,  166,  166,  167,  183,  128,  128,  129,  168,  168,
      168,  169,  169,  169,  170,  130,  127,  127,  131,  247,
      247,  172,  172,  173,  174,  174,  174,  175,  175,  175,
      135,  176,  132,  132,  177,  253,  179,  137,  137,  138,
      176,  176,  139,  177,  177,  140,  178,  136,  136,  141,
      182,  171,  142,  180,  180,  181,  143,  184,  184,  185,
      258,  258,  165,  145,  145,  146,  186,  186,  186,  187,
      187,  187,  188,  147,  144,  144,  148,  258,  258,  190,

      190,  191,  149,  192,  196,  150,  151,  197,  265,  265,
      194,  194,  195,  153,  153,  154,  196,  196,  155,  197,
      197,  265,  265,  152,  152,  157,  157,  158,  198,  198,
      198,  199,  199,  199,  159,  160,  156,  156,  200,  200,
      156,  161,  161,  162,  163,  160,  160,  164,  201,  207,
      207,  152,  208,  208,  202,  203,  203,  203,  203,  203,
      204,  205,  205,  206,  207,  168,  209,  208,  169,  170,
      165,  165,  144,  211,  211,  212,  172,  172,  173,  213,
      213,  213,  214,  214,  214,  215,  174,  171,  171,  175,
      225,  225,  217,  217,  218,  176,  219,  223,  177,  178,

      224,  271,  271,  221,  221,  222,  180,  180,  181,  223,
      223,  182,  224,  224,  225,  225,  179,  179,  184,  184,
      185,  183,  183,  186,  136,  234,  187,  226,  235,  227,
      132,  228,  127,  229,  230,  230,  231,  232,  232,  232,
      232,  232,  233,  188,  234,  196,  198,  235,  197,  199,
      190,  190,  191,  234,  192,  122,  235,  236,  236,  189,
      189,  194,  194,  195,  193,  193,  237,  207,  213,  112,
      208,  214,  238,  239,  239,  239,  239,  239,  240,  241,
      241,  242,  243,  263,  108,  263,  264,  254,  264,  245,
      245,  246,  247,  247,  256,  256,  257,  271,  271,  249,

      249,  249,  249,  249,  250,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  251,  209,  271,  271,  258,  258,
      259,  103,  211,  211,  212,  210,  210,  261,  261,  262,
      215,  223,  277,  234,  224,   99,  235,  217,  217,  218,
      263,  219,   93,  264,  265,  265,  216,  216,  221,  221,
      222,  220,  220,  266,  386,  386,  386,  386,  386,  386,
      268,  268,  269,  271,  271,  275,  275,  275,  236,  236,
      273,  273,  274,  275,  275,  275,  275,  275,  275,  275,
      278,   85,  279,   81,  280,   78,  281,  282,  282,  283,
      284,  284,  284,  284,  284,  285,  286,  286,  286,  286,

      286,  286,  293,  293,  293,  293,   72,  288,  288,  288,
      288,  288,  289,  290,  290,  290,  290,  290,  290,  290,
      290,  290,  290,  286,  286,  243,  247,  247,  293,  293,
      247,  247,  245,  245,  246,  244,  244,  247,  247,  292,
      247,  247,  247,  247,  258,  258,   66,  296,  296,  296,
      296,  296,  297,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  247,  247,  254,  302,  302,  263,  303,
      303,  264,  256,  256,  257,  302,  259,  302,  303,  301,
      303,  255,  255,  261,  261,  262,  304,  304,  304,  304,
      304,  304,  305,  265,  265,  266,   61,  260,  260,  307,

      307,  308,  268,  268,  269,  309,  309,  309,  309,  309,
      309,  271,  271,  271,  271,   57,  267,  267,  271,  271,
      271,  271,  271,  271,  271,  271,   50,  313,  313,  313,
      313,  313,  313,  313,  314,  315,  315,  271,  271,  320,
      320,  320,  320,  324,  324,  324,  286,  286,  286,  286,
      286,  286,   45,  318,  320,  320,  320,  320,  286,  286,
       36,  322,  322,  323,  324,  324,  324,  324,  324,  324,
      324,  281,  326,  286,  286,  293,  293,  247,  247,  378,
      329,  329,  329,  329,  329,  330,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  286,  286,  247,  247,

      247,  247,  202,  202,  202,  202,  304,  304,  340,  344,
      344,  229,  334,  247,  247,  342,  342,  343,  344,  344,
      338,  338,  338,  339,  202,  202,  202,  202,  202,  202,
      305,  309,  309,  344,  344,  271,  271,  307,  307,  308,
      306,  306,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  368,  349,  349,  349,  349,  349,  349,  350,
      229,  229,  229,  271,  271,  271,  271,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  367,
      354,  354,  354,  354,  354,  354,  354,  355,  356,  356,
      320,  320,  286,  286,  286,  286,  286,  286,  238,  238,

      238,  238,  386,  386,  386,  386,  359,  286,  286,  365,
      365,  351,  366,  366,  363,  363,  363,  364,  238,  238,
      238,  238,  238,  238,  340,  344,  344,  271,  271,  271,
      271,  342,  342,  343,  365,  271,  271,  366,  271,  271,
      341,  341,  271,  271,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  374,  386,  386,  320,
      320,  320,  320,  376,  376,  377,  372,  372,  372,  372,
      372,  372,  373,  281,  281,  281,  386,  386,  386,  386,
      365,  320,  320,  366,  320,  320,  320,  320,  320,  320,
      320,  320,  374,  379,  379,  379,  380,  380,  380,  376,

      376,  377,  385,  385,  379,  386,  386,  380,  381,  345,
      375,  375,  381,  385,  385,  383,  383,  384,  319,  383,
      383,  384,  385,  385,  385,  385,  310,  270,  125,  382,
      382,    4,    4,    4,  248,  248,  252,  252,  272,  272,
      276,  276,  287,  287,  291,  291,  294,  294,  295,  295,
      299,  299,  300,  300,  311,  311,  312,  312,  315,  315,
      316,  316,  317,  317,  321,  321,  325,  325,  327,  327,
      328,  328,  332,  332,  333,  333,  335,  335,  336,  336,
      337,  337,  346,  346,  347,  347,  348,  348,  229,  229,
      352,  352,  353,  353,  356,  356,  357,  357,  358,  358,

      360,  360,  361,  361,  362,  362,  369,  369,  370,  370,
      371,  371,  281,  281,   96,   90,   75,   69,   60,   54,
       53,   44,   43,   42,   41,   40,   39,   35,   30,   27,
       26,   23,   22,   21,   17,   16,   15,   12,  386,    3,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386
    } ;

static const flex_int16_t yy_chk[1272] =
    {   0,
        0,    1,   16,   21,   22,   24,   32,    1,   31,  467,
       42,  466,   24,   24,   24,   31,   31,   31,    1,   19,
      449,   19,   16,   21,   22,    1,    1,    1,    1,    2,
       42,    7,   32,   11,   33,    2,    7,   11,  434,   11,
      425,   33,   33,   33,   36,   37,    2,   36,   37,   45,
      160,  160,   45,    2,    2,    2,    2,   38,   39,   46,
       38,   41,   46,   38,   38,   39,   39,   39,   41,   41,
       41,   43,   50,   51,   55,   50,   51,   55,   43,   43,
       43,   47,   48,   57,   47,  424,   57,   47,   47,   48,
       48,   48,   52,   53,   58,   52,   54,   58,   52,   52,

       53,   53,   53,   54,   54,   54,   56,   61,   62,   66,
       61,   62,   66,   56,   56,   56,   59,  423,   63,   59,
       64,   63,   59,   59,   63,   63,  420,   64,   64,   64,
       67,   68,   69,   67,   68,  161,  161,   68,   68,   69,
       69,   69,   70,   71,   72,   70,   73,   72,  419,   73,
       71,   71,   71,   74,   75,   76,   74,   77,   76,   74,
       74,   75,   75,   75,   77,   77,   77,   78,   79,   80,
       78,   79,   80,  418,   81,   80,   80,   81,   82,   83,
       84,   82,   83,  183,  183,   83,   83,   84,   84,   84,
       85,   86,   87,   85,   86,   87,   89,   88,   87,   87,

       88,  184,  184,   89,   89,   89,   91,   92,   93,   91,
       94,   93,  417,   94,   92,   92,   92,   95,   96,   97,
       95,   98,   97,   95,   95,   96,   96,   96,   98,   98,
       98,   99,  100,  101,   99,  100,  101,  102,  103,  101,
      101,  103,  193,  193,  102,  102,  102,  104,  105,  106,
      104,  105,  106,  107,  105,  105,  108,  194,  194,  108,
      107,  107,  107,  109,  110,  111,  109,  110,  200,  200,
      110,  110,  111,  111,  111,  112,  113,  114,  112,  113,
      114,  116,  115,  114,  114,  115,  202,  202,  116,  116,
      116,  117,  118,  119,  117,  120,  119,  416,  121,  118,

      118,  118,  120,  120,  120,  121,  121,  121,  122,  123,
      124,  122,  123,  124,  125,  415,  124,  124,  126,  203,
      203,  125,  125,  125,  414,  126,  126,  126,  127,  128,
      129,  127,  128,  129,  131,  130,  129,  129,  130,  206,
      206,  131,  131,  131,  132,  133,  134,  132,  133,  134,
      135,  136,  134,  134,  136,  206,  413,  135,  135,  135,
      137,  138,  139,  137,  138,  139,  140,  138,  138,  141,
      142,  412,  141,  140,  140,  140,  143,  142,  142,  142,
      210,  210,  411,  143,  143,  143,  144,  145,  146,  144,
      145,  146,  148,  147,  146,  146,  147,  211,  211,  148,

      148,  148,  149,  150,  152,  149,  151,  152,  220,  220,
      150,  150,  150,  151,  151,  151,  153,  154,  155,  153,
      154,  221,  221,  154,  154,  155,  155,  155,  156,  157,
      158,  156,  157,  158,  159,  410,  158,  158,  162,  162,
      409,  159,  159,  159,  163,  162,  162,  163,  164,  165,
      166,  408,  165,  166,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  167,  168,  169,  167,  168,  170,
      167,  167,  407,  169,  169,  169,  170,  170,  170,  171,
      172,  173,  171,  172,  173,  175,  174,  173,  173,  174,
      225,  225,  175,  175,  175,  176,  177,  179,  176,  178,

      179,  229,  229,  177,  177,  177,  178,  178,  178,  180,
      181,  182,  180,  181,  185,  185,  181,  181,  182,  182,
      182,  185,  185,  186,  406,  189,  186,  187,  189,  187,
      405,  187,  404,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  188,  190,  196,  198,  190,  196,  198,
      188,  188,  188,  191,  192,  403,  191,  195,  195,  191,
      191,  192,  192,  192,  195,  195,  197,  207,  213,  402,
      207,  213,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  199,  216,  401,  217,  216,  208,  217,  199,
      199,  199,  204,  204,  208,  208,  208,  230,  230,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  205,
      205,  205,  205,  205,  205,  209,  233,  233,  212,  212,
      214,  400,  209,  209,  209,  212,  212,  214,  214,  214,
      215,  223,  233,  234,  223,  399,  234,  215,  215,  215,
      218,  219,  398,  218,  222,  222,  218,  218,  219,  219,
      219,  222,  222,  224,  227,  279,  227,  279,  227,  279,
      224,  224,  224,  231,  231,  232,  232,  232,  236,  236,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      235,  397,  235,  396,  235,  395,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  238,  238,  239,  239,

      240,  240,  244,  244,  245,  245,  394,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  241,  241,  241,
      241,  241,  241,  242,  242,  243,  247,  247,  246,  246,
      248,  248,  243,  243,  243,  246,  246,  249,  249,  242,
      250,  250,  252,  252,  258,  258,  393,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  251,  251,  251,
      251,  251,  251,  253,  253,  254,  255,  256,  263,  255,
      256,  263,  254,  254,  254,  257,  259,  302,  257,  253,
      302,  257,  257,  259,  259,  259,  260,  260,  261,  261,
      262,  262,  264,  265,  265,  266,  392,  262,  262,  264,

      264,  264,  266,  266,  266,  267,  267,  268,  268,  269,
      269,  271,  271,  272,  272,  391,  269,  269,  273,  273,
      274,  274,  275,  275,  276,  276,  390,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  277,  277,  281,
      281,  282,  282,  284,  284,  284,  286,  286,  287,  287,
      288,  288,  389,  277,  283,  283,  285,  285,  291,  291,
      388,  283,  283,  283,  283,  283,  283,  283,  283,  283,
      283,  378,  285,  289,  289,  293,  293,  294,  294,  368,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      290,  290,  290,  290,  290,  290,  292,  292,  295,  295,

      296,  296,  298,  298,  298,  298,  304,  304,  303,  306,
      306,  367,  292,  297,  297,  303,  303,  303,  307,  307,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      305,  309,  309,  308,  308,  311,  311,  305,  305,  305,
      308,  308,  312,  312,  313,  313,  314,  314,  315,  315,
      316,  316,  351,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  317,  317,  318,  318,  320,  320,  321,
      321,  322,  322,  323,  323,  324,  324,  325,  325,  345,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      326,  326,  327,  327,  328,  328,  329,  329,  331,  331,

      331,  331,  339,  339,  339,  339,  326,  330,  330,  341,
      342,  319,  341,  342,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  340,  344,  344,  346,  346,  347,
      347,  340,  340,  340,  343,  348,  348,  343,  349,  349,
      343,  343,  350,  350,  352,  352,  353,  353,  354,  354,
      356,  356,  357,  357,  358,  358,  366,  350,  350,  355,
      355,  359,  359,  366,  366,  366,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  364,  364,  364,  364,
      365,  369,  369,  365,  370,  370,  371,  371,  372,  372,
      373,  373,  374,  375,  376,  379,  375,  376,  379,  374,

      374,  374,  382,  382,  377,  373,  373,  377,  380,  310,
      377,  377,  381,  383,  383,  380,  380,  380,  280,  381,
      381,  381,  384,  384,  385,  385,  270,  228,   90,  384,
      384,  387,  387,  387,  421,  421,  422,  422,  426,  426,
      427,  427,  428,  428,  429,  429,  430,  430,  431,  431,
      432,  432,  433,  433,  435,  435,  436,  436,  437,  437,
      438,  438,  439,  439,  440,  440,  441,  441,  442,  442,
      443,  443,  444,  444,  445,  445,  446,  446,  447,  447,
      448,  448,  450,  450,  451,  451,  452,  452,  453,  453,
      454,  454,  455,  455,  456,  456,  457,  457,  458,  458,

      459,  459,  460,  460,  461,  461,  462,  462,  463,  463,
      464,  464,  465,  465,   65,   60,   49,   44,   40,   35,
       34,   30,   29,   28,   27,   26,   25,   23,   20,   18,
       17,   15,   14,   13,   10,    9,    8,    6,    3,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386,  386,  386,  386,  386,  386,  386,  386,  386,  386,
      386
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mPowAssemb.l"
#line 2 "mPowAssemb.l"
    #include<stdio.h>
    #include<string.h>
    #include<stdlib.h>
    #include<math.h>
    char instructionMatrix[100][100];
    int instrCount = 0;
    void convertbin(int , char*);
    void convertbincomp(int, char*, int);
    void convertbin6bit(int, char*);
    int pos[] = {6, 11, 16, 21, 26, 31};
#line 874 "lex.yy.c"
#line 875 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 17 "mPowAssemb.l"


#line 1095 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 387 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1240 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 19 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 4;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
        
    }
    strcat(instructionMatrix[instrCount], "01000010100\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 50 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "001110";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 5;

    for(int count = 0; count < 2; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
       
    }
    while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
    }
    int negativeflag = 0;
    if(temp[stringctrl] == '-') {
        negativeflag = 1;
        stringctrl++;
    }
    int count;
    for(count = 1; count <= 5; count++) {
        if(temp[stringctrl + count] ==  ' ' || temp[stringctrl+count] == ',' || temp[stringctrl+count] == '\0' || temp[stringctrl+count] == '\n'){
            break;
        }
    }
    int n = 0;
    for(int ctr = 0; ctr < count; ctr++) {
        n += (temp[stringctrl + ctr] - 48) * (int)(pow(10, count - ctr - 1));
    }
    char bin16num[17] = {0};
    if(negativeflag == 1) {
        convertbincomp(65536 - n, bin16num, negativeflag);
    } else {
        convertbincomp(n, bin16num, negativeflag);
    }
    strcat(instructionMatrix[instrCount], bin16num);
    strcat(instructionMatrix[instrCount], "\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 106 "mPowAssemb.l"
{
    char* temp = yytext;
    
    char* opcode = "001111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 6;

    for(int count = 0; count < 2; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
       
    }
    while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
    }
    int negativeflag = 0;
    if(temp[stringctrl] == '-') {
        negativeflag = 1;
        stringctrl++;
    }
    int count;
    for(count = 1; count <= 5; count++) {
        if(temp[stringctrl + count] ==  ' ' || temp[stringctrl+count] == ',' || temp[stringctrl+count] == '\0' || temp[stringctrl+count] == '\n'){
            break;
        }
    }
    int n = 0;
    for(int ctr = 0; ctr < count; ctr++) {
        n += (temp[stringctrl + ctr] - 48) * (int)(pow(10, count - ctr - 1));
    }
    char bin16num[17] = {0};
    if(negativeflag == 1) {
        convertbincomp(65536 - n, bin16num, negativeflag);
    } else {
        convertbincomp(n, bin16num, negativeflag);
    }
    strcat(instructionMatrix[instrCount], bin16num);
    strcat(instructionMatrix[instrCount], "\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 161 "mPowAssemb.l"
{
    char* temp = yytext;
    
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 4;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
       
    }
    strcat(instructionMatrix[instrCount], "00000111000\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 192 "mPowAssemb.l"
{
    char* temp = yytext;
    
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 5;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
        
    }
    strcat(instructionMatrix[instrCount], "00001010000\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 223 "mPowAssemb.l"
{
    char* temp = yytext;
    
    char* opcode = "011100";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 5;

    for(int count = 0; count < 2; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
       
    }
    while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
    }
    
    int count;
    for(count = 1; count <= 5; count++) {
        if(temp[stringctrl + count] ==  ' ' || temp[stringctrl+count] == ',' || temp[stringctrl+count] == '\0' || temp[stringctrl+count] == '\n'){
            break;
        }
    }
    int n = 0;
    for(int ctr = 0; ctr < count; ctr++) {
        n += (temp[stringctrl + ctr] - 48) * (int)(pow(10, count - ctr - 1));
    }
    char bin16num[17] = {0};
    convertbincomp(n, bin16num, 0);
    strcat(instructionMatrix[instrCount], bin16num);
    strcat(instructionMatrix[instrCount], "\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 270 "mPowAssemb.l"
{
    char* temp = yytext;
    
    char* opcode = "011000";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 4;

    for(int count = 0; count < 2; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
       
    }
    while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
    }
    
    int count;
    for(count = 1; count <= 5; count++) {
        if(temp[stringctrl + count] ==  ' ' || temp[stringctrl+count] == ',' || temp[stringctrl+count] == '\0' || temp[stringctrl+count] == '\n'){
            break;
        }
    }
    int n = 0;
    for(int ctr = 0; ctr < count; ctr++) {
        n += (temp[stringctrl + ctr] - 48) * (int)(pow(10, count - ctr - 1));
    }
    char bin16num[17] = {0};
    convertbincomp(n, bin16num, 0);
    strcat(instructionMatrix[instrCount], bin16num);
    strcat(instructionMatrix[instrCount], "\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 318 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 3;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
    }
    strcat(instructionMatrix[instrCount], "01101111000\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 348 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 5;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
    }
    strcat(instructionMatrix[instrCount], "01110111000\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 378 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "010101";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 7;

    for(int count = 0; count < 5; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
        
    }
    strcat(instructionMatrix[instrCount], "0\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 408 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 4;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
    }
    strcat(instructionMatrix[instrCount], "00000110110\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 438 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 4;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
    }
    strcat(instructionMatrix[instrCount], "10000110110\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 468 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 5;

    for(int count = 0; count < 3; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[7] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
    }
    strcat(instructionMatrix[instrCount], "11000110100\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 497 "mPowAssemb.l"
{
    char* temp = yytext;
   
    char* opcode = "011111";
    strcpy(instructionMatrix[instrCount], opcode);
    
    int stringctrl = 6;

    for(int count = 0; count < 2; count++) {
        int  instrctrl = pos[count];
        while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
        }
        char binregnum[6] = {0};

        if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
            convertbin((int)(temp[stringctrl]) - 48, binregnum);
            stringctrl++;
        } else{
            convertbin( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum);
            stringctrl += 2;
        }
        strcat(instructionMatrix[instrCount], binregnum);
    }
    while(temp[stringctrl] == ' ' || temp[stringctrl] == ',') {
            stringctrl++;
    }
    char binregnum6[7] = {0};
    if(temp[stringctrl + 1] ==  ' ' || temp[stringctrl+1] == ',' || temp[stringctrl+1] == '\0' || temp[stringctrl+1] == '\n') {
        convertbin6bit((int)(temp[stringctrl]) - 48, binregnum6);
        stringctrl++;
    } else {
        convertbin6bit( ((int)(temp[stringctrl]) - 48) * 10 + (int)temp[stringctrl + 1] - 48, binregnum6);
        stringctrl += 2;
    }
    strncat(instructionMatrix[instrCount], binregnum6, 5);
    strcat(instructionMatrix[instrCount], "0110011101");
    instructionMatrix[instrCount][30] = binregnum6[5];
    strcat(instructionMatrix[instrCount], "0\n");
    puts(instructionMatrix[instrCount]);
    instrCount++;
}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 540 "mPowAssemb.l"
{printf("\nA new line\n");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 541 "mPowAssemb.l"
;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 542 "mPowAssemb.l"
ECHO;
	YY_BREAK
#line 1736 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 387 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 387 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 386);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 542 "mPowAssemb.l"


int main(int arc, char **argv) {

    FILE* inputFile = fopen(argv[1], "r");
    yyin = inputFile;
    for(int i = 0; i < 100; i++) {
        for(int j = 0; j < 100; j++) {
            instructionMatrix[i][j] = 0;
        }
    }
    yylex();
    FILE* instrFp = fopen("instrfile.txt", "w");
    for(int k = 0; k < instrCount; k++) {
        fputs(instructionMatrix[k], instrFp);
    }
    fclose(inputFile);
    fclose(instrFp);
}

void convertbin(int n, char temp[]) {
    int i = 4;
    while(n) {
        temp[i--] = n % 2 + 48;
        n = n/2;

    }
    while(i >= 0) {
        temp[i] = '0';
        i--;
    }
}
void convertbincomp(int n, char temp[], int negativeflag) {
    int lastdig = negativeflag;
    int indx = 15;
    while(n) {
        temp[indx--] = n % 2 + 48;
        n = n / 2;
    }
    while(indx >= 0) {
        temp[indx--] = lastdig + 48;          
    }
}
void convertbin6bit(int n, char temp[]) {
    int i = 5;
    while(n) {
        temp[i--] = n % 2 + 48;
        n = n/2;

    }
    while(i >= 0) {
        temp[i] = '0';
        i--;
    }
}
