#!/usr/bin/env python3
 
import fileinput, sys
 
fname = sys.argv[1]
lf = open('linedet.txt', 'r');
lfdata = lf.readlines()
startdata = int(lfdata[0])
starttext = int(lfdata[1])
if startdata > starttext:
    start = startdata
    count = 200
else:
    start = startdata
    count = starttext
 
for line in fileinput.input(fname, inplace=1, backup='.orig'):
    if start <= fileinput.lineno() < start + count:
        pass
    else:
        print(line[:-1])
fileinput.close()